// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzbw9B6gp9TvVUTS8ey6MMIr7mbhh0CMU',
    appId: '1:533098343656:web:0add80e32a70c605046d5d',
    messagingSenderId: '533098343656',
    projectId: 'blog1-2b65d',
    authDomain: 'blog1-2b65d.firebaseapp.com',
    storageBucket: 'blog1-2b65d.appspot.com',
    measurementId: 'G-F5SSGNSCPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOBu11m4M2wxCHaFKYh7QxPQiRB-36790',
    appId: '1:533098343656:android:79ce040066442577046d5d',
    messagingSenderId: '533098343656',
    projectId: 'blog1-2b65d',
    storageBucket: 'blog1-2b65d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMm6QGE9IykQ3u0Xyvugus0U2ftCx0qqs',
    appId: '1:533098343656:ios:730fd43daa5aecf4046d5d',
    messagingSenderId: '533098343656',
    projectId: 'blog1-2b65d',
    storageBucket: 'blog1-2b65d.appspot.com',
    iosClientId: '533098343656-b0a96aesmgg8gp2c8j06ee8mkmdk2281.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMm6QGE9IykQ3u0Xyvugus0U2ftCx0qqs',
    appId: '1:533098343656:ios:730fd43daa5aecf4046d5d',
    messagingSenderId: '533098343656',
    projectId: 'blog1-2b65d',
    storageBucket: 'blog1-2b65d.appspot.com',
    iosClientId: '533098343656-b0a96aesmgg8gp2c8j06ee8mkmdk2281.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );
}
